version: "3.8"
services:
  db:
    image: postgres:14.1-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ml-ecommerce
    ports:
      - "5432:5432"
    volumes:
      # Persist db data
      - db:/var/lib/postgresql/data
      # Mount the schema file (init.sql)
      # - ./config/init.sql:/docker-entrypoint-initdb.d/init.sql
      # Mount the pgbench benchmark file (pgbench_names_of_customer_last_30_days.sql)
      - ./pgbench_names_of_customer_last_30_days.sql:/tmp/pgbench_names_of_customer_last_30_days.sql
      # Mount the pgbench file (pgbench_total_revenue.sql)
      - ./pgbench_total_revenue.sql:/tmp/pgbench_total_revenue.sql
      # Mount the pgbench benchmark file (pgbench_top_selling_prod.sql)
      - ./pgbench_top_selling_prod.sql:/tmp/pgbench_top_selling_prod.sql
volumes:
  db:
    driver: local
